# @package _global_


model:
  _target_: xlm.lm.ilm.model_ilm.RotaryTransformerILMModel
  num_embeddings: ${tokenizer:full_vocab_size}
  d_model: 768 # mdlm
  num_layers: 12
  nhead: 12
  padding_idx: ${tokenizer:pad_token_id}
  mask_idx: ${tokenizer:mask_token_id}
  dim_feedforward: ${eval:${.d_model}*4}
  dropout: 0.1
  activation: "relu"
  layer_norm_eps: 1e-5
  max_length: ${predictor.max_length}
  force_flash_attn: false

tags:
  model: rotary_transformer_small
  length_model: none