# @package _global_

defaults:
  - /metrics@reported_metrics.train.lm.accumulated_loss: accumulated_loss
  - /metrics@reported_metrics.val.lm.accumulated_loss: accumulated_loss
  - /metrics@reported_metrics.test.lm.accumulated_loss: accumulated_loss
  - /metrics@reported_metrics.val.prediction.exact_match: seq2seq_exact_match
  - /metrics@reported_metrics.test.prediction.exact_match: seq2seq_exact_match
  - /metrics@reported_metrics.val.prediction.token_accuracy: seq2seq_token_accuracy
  - /metrics@reported_metrics.test.prediction.token_accuracy: seq2seq_token_accuracy

lightning_module:
  _target_: xlm.harness.Harness

loss:
  _target_: xlm.lm.mlm.loss_mlm.MLMLoss

predictor:
  _target_: xlm.lm.mlm.predictor_mlm.MLMPredictor
  tokenizer: ${lightning_module:tokenizer}
  noise_schedule: ${lightning_module:noise_schedule}
  max_steps: ${block_size}
  # max_new_tokens should be non-null only for seq2seq, i.e. when input_block_size is set
  #max_new_tokens: ${if_else:${oc.select:input_block_size,false},${block_size},null}
  # assume seq2seq here
  max_new_tokens: ${block_size}
  top_k: 2
  top_p: null

diagnostic_metrics: null
reported_metrics:
  train:
    lm:
      accumulated_loss:
        prefix: train/lm
        update_fn: xlm.lm.mlm.metrics_mlm.mean_metric_update_fn
  val:
    lm:
      accumulated_loss:
        prefix: val/lm
        update_fn: xlm.lm.mlm.metrics_mlm.mean_metric_update_fn
    prediction:
      exact_match:
        prefix: val/prediction
        update_fn: xlm.lm.mlm.metrics_mlm.seq2seq_exact_match_update_fn
      token_accuracy:
        prefix: val/prediction
        update_fn: xlm.lm.mlm.metrics_mlm.seq2seq_token_accuracy_update_fn
  test:
    lm:
      accumulated_loss:
        prefix: test/lm
        update_fn: xlm.lm.mlm.metrics_mlm.mean_metric_update_fn
    prediction:
      exact_match:
        prefix: test/prediction
        update_fn: xlm.lm.mlm.metrics_mlm.seq2seq_exact_match_update_fn
      token_accuracy:
        prefix: test/prediction
        update_fn: xlm.lm.mlm.metrics_mlm.seq2seq_token_accuracy_update_fn

tags:
  model_type: mlm_seq2seq 