# @package _global_
defaults:
  - safe
  - /collator@datamodule.dataset_managers.train.lm.collator: default_flexmdm
  - /collator@datamodule.dataset_managers.val.lm.collator: default_flexmdm
  - /collator@datamodule.dataset_managers.test.lm.collator: default_flexmdm
  - /collator@datamodule.dataset_managers.val.unconditional_prediction.collator: unconditional_pred_flexmdm
  - /collator@datamodule.dataset_managers.predict.unconditional_prediction.collator: unconditional_pred_flexmdm
  - /collator@datamodule.dataset_managers.test.unconditional_prediction.collator: unconditional_pred_flexmdm

datamodule:
  print_batch_fn: flexmdm.datamodule_flexmdm.print_batch_flexmdm
  dataset_managers:
    val:
      unconditional_prediction:
        dataset_constructor_str: flexmdm.datamodule_flexmdm.FlexMDMEmptyDataset
        dataset_kwargs:
          max_length: ${datamodule.block_size}
    predict:
      unconditional_prediction:
        dataset_constructor_str: flexmdm.datamodule_flexmdm.FlexMDMEmptyDataset
        dataset_kwargs:
          max_length: ${datamodule.block_size}
      
    test:
      unconditional_prediction:
        dataset_constructor_str: flexmdm.datamodule_flexmdm.FlexMDMEmptyDataset
        dataset_kwargs:
          max_length: ${datamodule.block_size}

tags:
  dataset: safe

