defaults:
  - star_medium_train

collator: ??? # model specific collator
full_name: dhruveshpatel/star-medium/validation # dhruveshpatel/star-small/train # <repo>/<ds_name>/<split_to_download> . 
full_name_debug: dhruveshpatel/star-medium/train
stages: ["fit", "validate"]
