defaults:
  - star

collator: ??? # model specific collator
full_name: dhruveshpatel/star-small/train # dhruveshpatel/star-small/train # <repo>/<ds_name>/<split_to_download> . 
full_name_debug: dhruveshpatel/star-small/train
stages: ["fit"]
dataloader_kwargs:
    batch_size: ${per_device_batch_size} # per device, depends on the device type
    num_workers: ${num_dataloader_workers} 
    shuffle: null # can't specify shuffle for IterableDataset
    pin_memory: ${dataloader_pin_memory}
    persistent_workers: ${dataloader_persistent_workers} # INFO: see: https://github.com/huggingface/datasets/issues/7447
    prefetch_factor: ${dataloader_prefetch_factor}
    drop_last: True
model_name: null