defaults:
  - star_easy_train

collator: ??? # model specific collator
full_name: dhruveshpatel/star-small/test # dhruveshpatel/star-small/train # <repo>/<ds_name>/<split_to_download> . 
full_name_debug: dhruveshpatel/star-small/train
stages: ["test", "predict"]