# @package _global_
# four nodes, one gpu per node

slurm:
  nodes: 1
  gres: gpu:8
  ntasks_per_node: 8
  constrain: "vram80,bf16,ib"  # ib for infiniband
  partition: gpu,gpu-preempt,superpod-a100
  time: 8-00:00:00
  qos: long