# @package _global_
# four nodes, one gpu per node

slurm:
  nodes: 2
  gres: gpu:1
  ntasks_per_node: 1
  constrain: "vram80,bf16,ib"  # ib for infiniband
  partition: gpu,gpu-preempt,superpod-a100
  time: 02:00:00