_target_: xlm.metrics.MetricWrapper
name: token_ce
metric: 
  _target_: torchmetrics.MeanMetric
prefix: ??? # eg: train/lm/, val/lm/, test/lm/, etc.
update_fn: ??? # eg: xlm.lm.ilm.metrics_ilm.mean_metric_update_fn
