# @package _global_

noise_schedule:
  _target_: xlm.lm.idlm.noise_schedule.PoissonNoiseSchedule
  sigma: 10 # mdlm and sedd
  antithetic_sampling: false

tags:
  noise_schedule: poisson
  correlated_t: ${noise_schedule.antithetic_sampling}
  T: 1