# @package _global_

noise_schedule:
  _target_: xlm.noise_schedule.idlm.PoissonNoiseSchedule
  sigma: 50.0
  antithetic_sampling: false

tags:
  noise_schedule: poisson
  correlated_t: ${noise_schedule.antithetic_sampling}
  T: 1