# @package _global_

noise_schedule:
  _target_: xlm.lm.idlm.noise_schedule.GeometricNoiseSchedule
  sigma_max: 35
  sigma_min: 0.01
  antithetic_sampling: false

tags:
  noise_schedule: geometric
  correlated_t: ${noise_schedule.antithetic_sampling}
  T: 1