# @package _global_

noise_schedule:
  _target_: xlm.diffusion.absorbing.ContinuousTimeLinearSchedule
  sigma_min: 1e-3 # mdlm
  sigma_max: 7.0 # mdlm
  antithetic_sampling: false

tags:
  noise_schedule: discrete_time_linear
  correlated_t: ${noise_schedule.antithetic_sampling}
  T: 1