_target_: mlm.datamodule_mlm.DefaultInfillMLMCollator
block_size: ${block_size}
tokenizer: ${global_components:tokenizer}
noise_schedule: ${global_components:noise_schedule}
loss_on_padding: ${oc.select:loss_on_padding,true}
truncate: block
add_bos: ${oc.select:add_bos,false}
add_eos: ${oc.select:add_eos,true}
