# @package _global_
defaults:
  - default
  - /collator@datamodule.dataset_managers.train.lm.collator: seq2seq_zlm
  - /collator@datamodule.dataset_managers.val.lm.collator: seq2seq_zlm
  - /collator@datamodule.dataset_managers.test.lm.collator: seq2seq_zlm
  - /collator@datamodule.dataset_managers.val.prediction.collator: seq2seq_pred_zlm
  - /collator@datamodule.dataset_managers.test.prediction.collator: seq2seq_pred_zlm
  - /collator@datamodule.dataset_managers.predict.prediction.collator: seq2seq_pred_zlm

datamodule:
  print_batch_fn: zlm.collators.print_batch_zlm

tags:
  dataset: ??? 