# @package _global_

noise_schedule:
  _target_: xlm.noise_schedule.idlm.GeometricNoiseSchedule
  sigma_min: 1
  sigma_max: 40 # vstar_medium
  antithetic_sampling: false

tags:
  noise_schedule: geometric
  correlated_t: ${noise_schedule.antithetic_sampling}
  T: 1