_target_: xlm.lm.mlm.datamodule_mlm.DefaultMLMCollator
block_size: ${block_size}
tokenizer: ${global_components:tokenizer}
noise_schedule: ${global_components:noise_schedule}
loss_on_padding: true
truncate: block
add_bos: false
add_eos: true 