# @package _global_
defaults:
  - default
  - /datasets@datamodule.dataset_managers.train.lm: lm1b_train
  - /datasets@datamodule.dataset_managers.val.lm: lm1b_test
  - /datasets@datamodule.dataset_managers.val.unconditional_prediction: text_uncoditional_prediction
  - /collator@datamodule.dataset_managers.train.lm.collator: default_ilm
  - /collator@datamodule.dataset_managers.val.lm.collator: default_ilm
  - /collator@datamodule.dataset_managers.val.unconditional_prediction.collator: default_ilm


tags:
  dataset: lm1b