# @package _global_
defaults:
  - default
  - /datasets@datamodule.dataset_managers.train.lm: lm1b_train
  - /datasets@datamodule.dataset_managers.val.lm: lm1b_test
  - /datasets@datamodule.dataset_managers.val.unconditional_prediction: text_uncoditional_prediction


tags:
  dataset: lm1b