# @package _global_
defaults:
  - default
  - /datasets@datamodule.dataset_managers.train.lm: owt_train
  - /datasets@datamodule.dataset_managers.val.lm: owt_val
  - /datasets@datamodule.dataset_managers.val.unconditional_prediction: text_uncoditional_prediction

per_device_batch_size: 32
global_batch_size: 512
input_block_size: null
block_size: 1024

global_components:
  tokenizer:
    _target_: xlm.datamodule.GPT2TokenizerFast.from_pretrained
    pretrained_model_name_or_path: gpt2


tags:
  dataset: owt