# @package _global_
defaults:
  - owt
  - /collator@datamodule.dataset_managers.train.lm.collator: default_ilm
  - /collator@datamodule.dataset_managers.val.lm.collator: default_ilm
  - /collator@datamodule.dataset_managers.val.unconditional_prediction.collator: unconditional_pred_ilm


tags:
  dataset: owt