# @package _global_

defaults:
  - /metrics@reported_metrics.train.lm.accumulated_loss: accumulated_loss
  - /metrics@reported_metrics.val.lm.accumulated_loss: accumulated_loss
  - /metrics@reported_metrics.test.lm.accumulated_loss: accumulated_loss
  - /metrics@reported_metrics.val.prediction.exact_match: seq2seq_exact_match
  - /metrics@reported_metrics.test.prediction.exact_match: seq2seq_exact_match
  - /metrics@reported_metrics.val.prediction.token_accuracy: seq2seq_token_accuracy
  - /metrics@reported_metrics.test.prediction.token_accuracy: seq2seq_token_accuracy

lightning_module:
  _target_: xlm.harness.Harness

loss:
  _target_: flexmdm.loss_flexmdm.FlexMDMLoss
  loss_on_padding: true
  loss_on_visible_tokens: false
  insert_loss_fn: ${len_predict_type} # choices: 'expectation', 'distribution'
  noise_schedule: ${global_components:noise_schedule}

predictor:
  _target_: flexmdm.predictor_flexmdm.FlexMDMPredictor
  tokenizer: ${global_components:tokenizer}
  noise_schedule: ${global_components:noise_schedule}
  max_steps: ${block_size}
  # max_new_tokens should be non-null only for seq2seq, i.e. when input_block_size is set
  #max_new_tokens: ${if_else:${oc.select:input_block_size,false},${block_size},null}
  # assume non-seq2seq here
  max_new_tokens: null
  top_k: 1 
  top_p: null
  len_predict_type: ${len_predict_type}

diagnostic_metrics: null
reported_metrics:
  train:
    lm:
      accumulated_loss:
        prefix: train/lm
        update_fn: flexmdm.metrics_flexmdm.mean_metric_update_fn
  val:
    lm:
      accumulated_loss:
        prefix: val/lm
        update_fn: flexmdm.metrics_flexmdm.mean_metric_update_fn
    prediction:
      exact_match:
        prefix: val/prediction
        update_fn: flexmdm.metrics_flexmdm.seq2seq_exact_match_update_fn
      token_accuracy:
        prefix: val/prediction
        update_fn: flexmdm.metrics_flexmdm.seq2seq_token_accuracy_update_fn
  test:
    lm:
      accumulated_loss:
        prefix: test/lm
        update_fn: flexmdm.metrics_flexmdm.mean_metric_update_fn
    prediction:
      exact_match:
        prefix: test/prediction
        update_fn: flexmdm.metrics_flexmdm.seq2seq_exact_match_update_fn
      token_accuracy:
        prefix: test/prediction
        update_fn: flexmdm.metrics_flexmdm.seq2seq_token_accuracy_update_fn

tags:
  model_type: flexmdm_seq2seq
