# @package _global_
defaults:
  - owt
  - /collator@datamodule.dataset_managers.train.lm.collator: default_mdlm
  - /collator@datamodule.dataset_managers.val.lm.collator: default_mdlm
  - /collator@datamodule.dataset_managers.val.unconditional_prediction.collator: unconditional_pred_mdlm
  - /collator@datamodule.dataset_managers.predict.unconditional_prediction.collator: unconditional_pred_mdlm

datamodule:
  print_batch_fn: xlm.lm.mdlm.datamodule_mdlm.print_batch_mdlm
  dataset_managers:
    val:
      unconditional_prediction:
        dataset_constructor_str: xlm.lm.mdlm.datamodule_mdlm.MDLMEmptyDataset
        dataset_kwargs:
          max_length: ${datamodule.block_size}
    predict:
      unconditional_prediction:
        dataset_constructor_str: xlm.lm.mdlm.datamodule_mdlm.MDLMEmptyDataset
        dataset_kwargs:
          max_length: ${datamodule.block_size}

tags:
  dataset: owt 