# @package _global_
defaults:
  - default
  - /collator@datamodule.dataset_managers.train.lm.collator: seq2seq_elm
  - /collator@datamodule.dataset_managers.val.lm.collator: seq2seq_elm
  - /collator@datamodule.dataset_managers.test.lm.collator: seq2seq_elm
  - /collator@datamodule.dataset_managers.val.prediction.collator: seq2seq_pred_elm
  - /collator@datamodule.dataset_managers.test.prediction.collator: seq2seq_pred_elm
  - /collator@datamodule.dataset_managers.predict.prediction.collator: seq2seq_pred_elm

datamodule:
  print_batch_fn: xlm.lm.elm.datamodule_elm.print_batch_elm
  dataset_managers:
    train:
      lm:
        collator:
          add_bos: true
    val:
      lm:
        collator:
          add_bos: true
      prediction:
        collator:
          add_bos: true
    test:
      lm:
        collator:
          add_bos: true
      prediction:
        collator:
          add_bos: true
    predict:
      prediction:
        collator:
          add_bos: true


tags:
  dataset: ??? 