# @package _global_
defaults:
  - default
  - /collator@datamodule.dataset_managers.train.lm.collator: seq2seq_indigo
  - /collator@datamodule.dataset_managers.val.lm.collator: seq2seq_indigo
  - /collator@datamodule.dataset_managers.test.lm.collator: seq2seq_indigo
  - /collator@datamodule.dataset_managers.val.prediction.collator: seq2seq_pred_indigo
  - /collator@datamodule.dataset_managers.test.prediction.collator: seq2seq_pred_indigo
  - /collator@datamodule.dataset_managers.predict.prediction.collator: seq2seq_pred_indigo

datamodule:
  print_batch_fn: xlm.lm.indigo.datamodule_indigo.print_batch_indigo

tags:
  dataset: ??? 