_target_: xlm.lm.indigo.datamodule_indigo.DefaultIndigoCollator
block_size: ${block_size}
tokenizer: ${global_components:tokenizer}
noise_schedule: ${global_components:noise_schedule}
# TODO (URV): Add indigo-specific collator parameters 