# @package _global_
trainer:
  max_epochs: 3
  limit_train_batches: 1000
  limit_val_batches: 10
  limit_test_batches: 10
  num_sanity_val_steps: 2
  val_check_interval: null
  check_val_every_n_epoch: 1