# @package _global_
defaults:
  - default
  - /datasets@datamodule.dataset_managers.train.lm: lm1b_train
  - /datasets@datamodule.dataset_managers.val.lm: lm1b_test
  - /collator@datamodule.dataset_managers.train.lm.collator: default_arlm
  - /collator@datamodule.dataset_managers.val.lm.collator: default_arlm

datamodule:
  print_batch_fn: arlm.datamodule_arlm.print_batch_arlm

tags:
  dataset: lm1b 