defaults:
    - default_text

_target_: xlm.datamodule.DatasetManager
collator: ??? # model specific collator
full_name: brozonoyer/sapientinc-sudoku-extreme-timvink-sudoku-solver/train
full_name_debug: brozonoyer/sapientinc-sudoku-extreme-timvink-sudoku-solver/train
preprocess_function: xlm.tasks.sudoku_extreme.sudoku_extreme_preprocess_fn
on_the_fly_processor: xlm.datamodule.token_ids_to_input_ids_and_prompt_ids
on_the_fly_group_processor: null
columns_to_remove:
    - rating
stages:
    - fit
iterable_dataset_shards: null
shuffle_buffer_size: null
shuffle_seed: 42
split_by_node: true
dataloader_kwargs:
    batch_size: ${per_device_batch_size}
    num_workers: ${num_dataloader_workers}
    shuffle: null
    pin_memory: True
    persistent_workers: False
    prefetch_factor: ${dataloader_prefetch_factor}
    drop_last: True
model_name: null
