defaults:
    - sudoku_train
    - _self_

full_name: ${oc.env:DATA_DIR,.}/sudoku/test # <repo>/<ds_name>/<split_to_download> .
full_name_debug: ${oc.env:DATA_DIR,.}/sudoku/train
stages:
    - fit
    - validate
