_target_: flexmdm.datamodule_flexmdm.FlexMDMTrainCollator
input_block_size: ${input_block_size} # we expect input_block_size to be set in the experiment config
block_size: ${block_size}
tokenizer: ${global_components:tokenizer}
